---
  swagger: "2.0"
  info: 
    title: "Agora-Board"
    description: "Public Bulletin Board with Fiware-Orion Backend"
    version: "0.0.1"
  host: localhost:9000
  schemes:
    - "http"
  consumes:
    - application/json
  produces: 
    - application/json
  definitions:
    contributors:
      type: object
      properties:
        id:
          type: integer
        id_str:
          type: string
        screen_name:
          type: string