---
  swagger: "2.2"
  info: 
    title: "Agora-Board"
    description: "Public Bulletin Board with Fiware-Orion Backend"
    version: "1.0.0"
  host: localhost:9000
  schemes:
    - "http"
  produces: 
    - application/json
  consumes: 
    - application/json
  definitions:
    DSAPublicKeyString:
      type: object
      required:
        - y
        - p
        - q
        - g
      properties:
        y:
          type: string
        p:
          type: string
        q:
          type: string
        g:
          type: string
    SignatureElements:
      type: object
      required:
        - first
        - second
        - zmod
      properties:
        first:
          type: string
        second:
          type: string
        zmod:
          type: string
    SignatureString:
      type: object
      required:
        - signerPK
        - signaturePK
        - signature
      properties:
        signerPK:
          $ref: "#/definitions/DSAPublicKeyString"
        signaturePK:
          type: string
        signature:
          $ref: "#/definitions/SignatureElements"
    PostRequest:
      type: object
      required:
        - message
        - user_attributes
      properties:
        message:
          type: string
        user_attributes:
          $ref: "#/definitions/UserAttributes"
    UserAttributes:
      type: object
      required:
        - section
        - group
        - pk
      properties:
        section:
          type: string
        group:
          type: string
        pk:
          type: string
        signature:
          $ref: "#/definitions/SignatureString"
    BoardAttributes:
      type: object
      required:
        - index
        - timestamp
        - hash
      properties:
        index:
          type: string
        timestamp:
          type: string
        hash:
          type: string
        signature:
          $ref: "#/definitions/SignatureString"
    Post:
      type: object
      required:
        - message
        - user_attributes
        - board_attributes
      properties:
        message:
          type: string
        user_attributes:
          $ref: "#/definitions/UserAttributes"
        board_attributes:
          $ref: "#/definitions/BoardAttributes"
    GetRequest:
      type: object
      required:
        - section
        - group
        - index
      properties:
        section:
          type: string
        group:
          type: string
        index:
          type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string
    